stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - git remote add github git@github.com:kstacker/kstacker.git
    - git push github --mirror
  only:
    - main  # ou la branche que tu veux synchroniser